#%RAML 0.8
title: "GestaltNotifier"
version: "1.2.5"
baseUri: "https://notifier.galacticfog.com:5309"
securitySchemes:
  - basic:
      type: Basic Authentication
securedBy: [ null, basic ]
schemas: 
    - 
        Message: '{"type":"object","description":"Message format","title":"Message","properties":{"messageId":{"type":"string","required":true,"title":"messageId"},"source":{"type":"string","required":true,"title":"source"},"date":{"type":"string","required":true,"title":"date"},"to":{"type":"string","required":true,"title":"to"},"from":{"type":"string","required":true,"title":"from"},"body":{"type":"string","required":true,"title":"body"},"subject":{"type":"string","required":false,"title":"subject"},"inResponseTo":{"type":"string","required":false,"title":"inResponseTo"}}}'
        SourceCreate: '{"type":"object","title":"SourceCreate","properties":{"sourceType":{"type":"string","required":true,"title":"sourceType"},"config":{"type":"object","$ref":"#/schemas/Config","required":false,"title":"config"},"handler":{"type":"object","$ref":"#/schemas/HandlerCreate","required":false,"title":"handler"}}}'
        Config: '{"type":"object","description":"JSON configuration for a source, sink or handler","title":"Config"}'
        HandlerCreate: '{"type":"object","title":"HandlerCreate","properties":{"handlerType":{"type":"string","required":true,"title":"handlerType"},"config":{"type":"object","$ref":"#/schemas/Config","required":false,"title":"config"}}}'
        SinkCreate: '{"type":"object","description":"Configuration for creating a sink","title":"SinkCreate","properties":{"sinkType":{"type":"string","required":true,"title":"sinkType"},"config":{"type":"object","$ref":"#/schemas/Config","required":false,"title":"config"}}}'
/sources: 
    displayName: Sources
    description: Operations on sources
    get: 
    post: 
/sinks: 
    displayName: Sinks
    description: Operations on sinks
    get: 
    post: 
        description: Create a new sink, used for sinking message to a particular outbound adapter.
        body: 
            application/json: 
                schema: SinkCreate
                example: '{"config":null,"sinkType":"sample sinkType"}'
        responses: 
            "200": 
                description: Sink was successfully created.
/handlers/types: 
    displayName: Handlers
    description: Operations on handlers
    get: 
/statusAll: 
    displayName: StatusAll
    description: Status on all sources and sinks
    get: 
/health: 
    displayName: Health
    description: Health checking
    get: 
/sinks/{sinkId}: 
    displayName: Sink
    description: Operations on a specific sink
    uriParameters: 
        sinkId: 
            displayName: sinkId
            description: ID of the target sink
            type: string
            required: false
            repeat: false
    get: 
    post: 
        body: 
            application/json: 
                schema: Message
                example: '{"to":"sample to","body":"sample body","source":"sample source","subject":"sample subject","from":"sample from","date":"sample date","messageId":"sample messageId","inResponseTo":"sample inResponseTo"}'
        responses: 
            "200": 
    delete: 
/sources/{sourceId}: 
    displayName: Source
    description: Operations on a specific source
    uriParameters: 
        sourceId: 
            displayName: sourceId
            description: ID of target source
            type: string
            required: false
            repeat: false
    get: 
        description: Get a specific sink
    delete: 
        description: Delete a specific sink.
